Number conversion
emmanueltukpe/20-days-challenge pull request #7
Opened 2020-08-19 14:09 UTC by emmanueltukpe

Resolved #5

2020-08-19 19:57 UTC, jirevwe requested changes

2020-08-19 19:57 UTC, jirevwe commented on words_in_reverse.py
> +sliced_string = ten_word_string[string_length::-1]
This file was merged yesterday, remove it and reopen another PR

2020-08-19 19:58 UTC, jirevwe commented
Remove the `words_in_reverse.py` and reopen another PR

2020-08-20 09:00 UTC, emmanueltukpe commented
Removed the words_in_reversed.py

2020-08-20 09:19 UTC, jirevwe approved these changes

2020-08-20 09:19 UTC, jirevwe commented
Create a new PR without that second file. I can't rebase the branch cleanly

2020-08-20 09:19 UTC, closed without merging

2020-08-20 09:20 UTC, jirevwe commented
Also, you can create a new branch